remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

title: "Christopher Dale"
name: "Christopher Dale"
description: "Strategic leader in analytics and operational systems"
url: "https://thebookofdale.github.io"
baseurl: "" # leave blank for user site

plugins:
  - jekyll-remote-theme